export const styles = {
  container: {
    width: "100%",
    minHeight: "100vh",
    height: "auto",
    background: "#000",
  },
  Navtitle: {
    fontSize: "20px",
    fontWeight: "600",
  },
  modalBox: {
    width: "100%",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  modalStyles: {
    outline: "none",
    width: { xs: "300px", sm: "400px", md: "500px" },
    display: "flex",
    flexDirection: "column",
    background: "#fff",
    padding: "15px 30px",
    borderRadius: "20px",
    position: "relative",
    margin: { xs: "0 15px" },
  },
  modalqueryHead: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "10px",
    padding: "10px",
  },
  qrBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    width: "300px",
    height: "250px",
    background: "#F7F8FC",
  },
  generateBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px",
  },
  generateNew: {
    display: "flex",
    alignItems: "center",
    padding: "10px",
    boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    borderRadius: "10px",
    cursor: "pointer",
    background: "#fff",
  },
  buttontitle: {
    fontWeight: "600",
    marginLeft: "5px",
  },
  qrboxhead: {
    fontFamily: "Inter, system-ui, Avenir, Helvetica, Arial, sans-serif",
  },
  showQr: {
    background: "#06B0E8",
    textAlign: "center",
    color: "#fff",
    width: { md: "150px" },
    padding: "15px 10px",
    borderRadius: "25px",
    cursor: "pointer",
    fontWeight: "600",
  },
  textFieldBoxmedium: {
    margin: "25px 0",
    display: { xs: "none", sm: "block", md: "block" },
  },
  textFieldBoxsmall: {
    margin: "25px 0",
    display: { xs: "block", sm: "none", md: "none" },
  },
  sendBtn: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    textAlign: { xs: "center", md: "center" },
  },
  send: {
    background: "#06B0E8",
    color: "#fff",
    width: { xs: "100px", sm: "150px", md: "200px" },
    padding: "15px 10px",
    borderRadius: "25px",
    cursor: "pointer",
    fontWeight: "600",
  },
  cancel: {
    background: "#fff",
    border: "2px solid #06B0E8",
    color: "#06B0E8",
    fontWeight: "600",
    width: { xs: "100px", sm: "150px", md: "200px" },
    padding: "15px 10px",
    borderRadius: "25px",
    cursor: "pointer",
  },
  closeBox: {
    position: "absolute",
    right: -10,
    top: -10,
    background: "#fff",
    boxShadow: "rgba(0, 0, 0, 0.1) 0px 4px 12px",
    width: "35px",
    height: "35px",
    borderRadius: "50%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
  },
  allQrBox: {
    padding: "30px",
    display: "flex",
    justifyContent: "center",
    margin: "25px 0",
    flexWrap: "wrap",
  },
  qrContainer: {
    display: "flex",
    justifyContent: "center",
    margin: "10px 20px",
    width: "250px",
    padding: "20px",
    background: "#f7f8fc",
    borderRadius: "20px",
    boxShadow:
      "rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset",
    flexDirection: "column",
  },
  qrbtnbox: {
    margin: "10px 0",
    width: "100%",
    textAlign: "center",
  },
  reuse: {
    background: "#06B0E8",
    color: "#fff",
    padding: "10px",
    borderRadius: "25px",
    cursor: "pointer",
    fontWeight: "600",
  },
};
